site_name: Manual de Instalación - Santiago Seguros
theme:
  name: material
  language: es
  features:
    - navigation.sections
    - toc.integrate
    - content.code.copy
nav:
  - Manual de Instalación: index.md
